### ISSUE TITLE
number of miles per 1 degree of lattitude 

### ISSUE THREAD

**Issue by AirDrug** [MoffKalast/Sailwind-Map#4]
why  is it 90 NM per 1 degree    and not 60 NM ??

**Comment by MoffKalast** [comment]
Yeah honestly I'm not sure what's up with that exactly, but the degrees to NM function has been set up that way since before I did the rework and most everyone in the game discord seems to agree that's correct. Probably something to do with the 1 NM = 100 m thing with the scaled down world and whatnot, so that sun and star navigation works out properly. :shrug: 

I've never verified if it's correct or not, but it should be possible by finding two spots with a known distance in degrees between them, sailing from one to the other and figuring out the distance according to the wiki:

> You can use the chip log to measure distance traveled. To transpose the distance into miles from knots, multiply the speed by 1.15, then multiply by the time in hours
